In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from scipy.sparse import csc_matrix

In [2]:
def load_movielens(mean_adjust = 'user'):
    '''Loads movielens set into a Dataframe. Adjusted rating is user by default'''
    path = 'ml-latest-small\\'
    df = pd.read_csv(path + 'ratings.csv')
    movie_xref = pd.read_csv(path + 'movies.csv')
    users = df.groupby('userId').mean()['rating'].reset_index()
    users['user_mean_rating'] = users['rating']
    users['uid'] = users.index
    users.drop('rating',inplace=True,axis=1)
    df = df.merge(users,left_on='userId',right_on='userId')
    movies = df.groupby('movieId').mean()['rating'].reset_index()
    movies['movie_mean_rating'] = movies['rating']
    movies = movies.merge(movie_xref,left_on='movieId',right_on='movieId')
    movies.drop('rating',inplace=True,axis=1)
    movies['mid'] = movies.index
    df = df.merge(movies,left_on='movieId',right_on='movieId')
    if mean_adjust == 'user':
        df['adjusted_rating'] = df['rating'] - df['user_mean_rating']
    elif mean_adjust == 'movie':
        df['adjusted_rating'] = df['rating'] - df['movie_mean_rating']
    return df

# Naive Bayes

In [3]:
df = load_movielens()
users_list = df['uid']
movies_list = df['mid']
ratings_list = df['rating']
df_sparse = csc_matrix((ratings_list,(users_list,movies_list)))

In [73]:
def calculate_priors(df):
    m_ct = df.groupby('mid').count()['uid'].reset_index()
    mr_ct = df.groupby(['mid','rating']).count()['uid'].reset_index()
    total_ct = m_ct.merge(mr_ct,left_on='mid',right_on='mid')
    total_ct['prob'] = total_ct['uid_y']/total_ct['uid_x']
    return total_ct[['mid','rating','prob']]

def calculate_priors_sparse(df_sparse,laplacian = None):
    '''laplacian should be a floating point'''
    '''This takes a sparse matrix which has as columns the set of items to be rated'''
    '''The rows are each one user.'''
    '''Nonzero entries are ratings of items they have rated'''
    
    num_cols = df_sparse.shape[1]
    all_ratings = list(set(df_sparse.data))
    all_ratings = all_ratings
    all_ratings = sorted(all_ratings)
    num_ratings = len(all_ratings)
    ct_df = np.zeros((num_cols,num_ratings))

    for c in range(num_cols):
        #counts the number of unique ratings (per column) and how many times that rating occurred
        unq,cts = np.unique(df_sparse[:,c].toarray(),return_counts=True)
        d = dict(zip(unq, cts))
        d = {k:v for k,v in d.items() if k > 0}
        rating_dict = {rating:0 for rating in all_ratings}
        for k,v in d.items():
            rating_dict[k] = v
        #d = {k:v for k,v in d.items() if k!=0}
        ct_df[c] = [i[1] for i in sorted(rating_dict.items(),key=lambda x: x[0])]
    #This dataframe now has rows which are films, columns which are ratings, and each entry has the number of times
    #which that particular rating occurred for that particular film
    ct_df = pd.DataFrame(ct_df)
    ct_df.columns = all_ratings
    numerator_cols = ct_df.columns
    ct_df['rowsum'] = ct_df.sum(axis=1)

    if laplacian is not None:
        ct_df[numerator_cols] = ct_df[numerator_cols].fillna(0) + laplacian
        ct_df['rowsum'] = ct_df['rowsum'].fillna(0) + laplacian * len(numerator_cols)
    ct_df = ct_df.apply(lambda x: x/x.rowsum,axis=1)
    ct_df = ct_df.drop('rowsum',axis=1)
    ct_df = ct_df.unstack().reset_index()
    ct_df.columns = ['rating','mid','prob']
    return ct_df

#Will need to fix this similarly to the above
def calculate_conditional(df,rating_vs,rating_k,j,k,laplacian = None):
    '''
    df is the sparse dataframe containing the data to be trained/rated
    rating_vs is the rating that we're comparing against for the conditional - 
        P(r_uk | r_uj = v_s), what's the likelihood that we observed rating r_uk for item k (user u) given that
        user u gave item j the rating v_s
    '''
    total_users = df.shape[0]
    df_j = df[:,j]
    #Find set of users who rated item j rating
    users = (df_j == rating_vs).nonzero()[0]
    num_users = len(users)
    #Of those users, how many rated item k the same as the original user?
    df_k = df_sparse[users,k]
    nz = df_k.nonzero()
    nzk = df_k[nz[0]].toarray()
    unq,cts = np.unique(nzk,return_counts=True)
    ct = []

    d = dict(zip(unq, cts))
    d = {k:v for k,v in d.items() if k!=0}
    ct.append(d)
    #This dataframe now has rows which are films, columns which are ratings, and each entry has the number of times
    #which that particular rating occurred for that particular film
    ct_df = pd.DataFrame(ct)
    numerator_cols = ct_df.columns
    ct_df['rowsum'] = ct_df.sum(axis=1)

    if laplacian is not None:
        ct_df[numerator_cols] = ct_df[numerator_cols].fillna(0) + laplacian
        ct_df['rowsum'] = ct_df['rowsum'].fillna(0) + laplacian * total_users
    try:
        retval = (ct_df[rating_vs].values/ct_df['rowsum'].values)[0]
    except:
        retval = 1/total_users
    return retval
    
def calculate_rating(df,user,item,laplacian = None):
    '''
    df: sparse array (csc?) containing the data to be predicted
    user is index of user to look at
    item is item to be rated
    
    for all items that the user rated, we need to see, for each rating possible to use,
    what the likelihood is that user rated item, that rating. In order to do so, we use the formula:
    
    P(r_uj = v_s | Observed ratings of user u) is proportional to P(r_uj = v_s) * PI(P(r_uk | r_uj = v_s) for k in I_u)
    Where I_u is the set of items that user u has rated
    P(r_uj = vs) is called the prior probability, and we'll need to calculate that for each item first
    P(r_uk | r_uj = v_s) is called the conditional probability.
    '''
    
    #priors contains the prior probabilities for all items
    #for a given item, it's the list of all ratings and what ratio, 
    #for each rating for that item, what was the likelihood it occurred
    priors = calculate_priors_sparse(df,laplacian = laplacian)
    vals = list(set(df.data))
    num = 0
    denom = 0
    user_items = df[user,:].nonzero()[1]
    for i in range(len(vals)):
        vs = vals[i]
        try:
            prior = priors.loc[(priors['mid']==item)&(priors['rating']==vs),'prob'].values[0]
        except:
            prior = 0
            continue
        mult = 1
        for k in user_items:
            user_rating = df[user,k]
            conditional = calculate_conditional(df,vs,user_rating,item,k,laplacian = laplacian)
            mult = mult * conditional 
            if np.isnan(conditional or np.isnan(prior)):
                print('vs: %0.3f rating: %0.3f item: %i k: %i')
        num += vs*prior*mult
        denom += denom + prior * mult
    return num/denom

def print_user_movies(df,user):
    movies = df.loc[df['uid']==user,'title']
    print(movies)

In [100]:
test = [
    [1,-1,1,-1,1,-1],
    [1,1,0,-1,-1,-1],
    [0,1,1,-1,-1,0],
    [-1,-1,-1,1,1,1],
    [-1,0,-1,1,1,1]
]
test_array = np.array(test)
test_sparse = csc_matrix(test_array)

In [58]:
p = calculate_priors_sparse(df_sparse,laplacian=0.8)

In [63]:
r = calculate_rating(df_sparse,2,1,laplacian = 0.8)

In [85]:
r = calculate_rating(df_sparse,2,321,laplacian=0.8)

In [87]:
#Why is this coming out 0.25????
r

0.25000000045839021

In [80]:
df.loc[(df['uid']==2)&(df['mid']==321)]

userId  movieId  rating   timestamp  user_mean_rating  uid  \
4477       3      356     5.0  1298862167          3.568627    2   

      movie_mean_rating                title                    genres  mid  \
4477           4.054252  Forrest Gump (1994)  Comedy|Drama|Romance|War  321   

      adjusted_rating  
4477         1.431373

In [75]:
print_user_movies(df,2)

1780                                     Braveheart (1995)
3652                                   Pulp Fiction (1994)
4477                                   Forrest Gump (1994)
5418                                          Speed (1994)
6892                               Schindler's List (1993)
7718                                        Aladdin (1992)
8372                                         Batman (1989)
8568                      Silence of the Lambs, The (1991)
9011                    Indian in the Cupboard, The (1995)
9043                             Heavenly Creatures (1994)
9086                                    Major Payne (1995)
9099                      Shawshank Redemption, The (1994)
9410                               Flintstones, The (1994)
9449                           Beauty and the Beast (1991)
9625                                        Twister (1996)
9775                                  Trainspotting (1996)
9899                                          Bound (199

In [72]:
df[df['mid']==1]

userId  movieId  rating   timestamp  user_mean_rating  uid  \
41777      15        2     2.0  1134521380          2.621765   14   
41778      19        2     3.0   855194773          3.534279   18   
41779      30        2     2.0   945277634          3.765084   29   
41780      32        2     4.0   834828285          3.666667   31   
41781      41        2     3.5  1093888283          3.866834   40   
41782      47        2     5.0   832229657          3.868421   46   
41783      48        2     3.5  1322169967          3.514620   47   
41784      49        2     5.0   978040739          3.464646   48   
41785      61        2     3.5  1216051639          3.274096   60   
41786      68        2     3.0  1249809905          3.626016   67   
41787      69        2     3.5  1366831701          4.135802   68   
41788      72        2     2.5  1461784724          3.243455   71   
41789      73        2     2.5  1255595527          3.374224   72   
41790      78        2     3.5  1274051069          4.298479   77   
41791      79        2     2.5  1182994926          2.518182   78   
41792      80        2     2.0   844860022          3.594595   79   
41793      85        2     5.0   837511784          3.186916   84   
41794      88        2     3.5  1239773232          3.378431   87   
41795      92        2     3.0   848525932          3.154472   91   
41796      99        2     2.0   950999958          3.430851   98   
41797     113        2     5.0   844884330          4.629630  112   
41798     115        2     5.0  1107034391          4.109756  114   
41799     119        2     3.0   913051445          3.500780  118   
41800     124        2     3.0  1147861200          3.758824  123   
41801     126        2     3.0   833286607          3.609375  125   
41802     128        2     4.0  1049685256          3.860681  127   
41803     134        2     4.5  1361245855          4.008039  133   
41804     150        2     3.0  1114306834          3.113801  149   
41805     151        2     4.0   847296918          3.734375  150   
41806     157        2     2.5  1291654669          3.400307  156   
...       ...      ...     ...         ...               ...  ...   
41854     480        2     5.0  1272669458          3.998677  479   
41855     487        2     4.0   832836515          3.769737  486   
41856     496        2     4.0   834060098          3.912698  495   
41857     500        2     1.5  1228946281          2.981928  499   
41858     506        2     3.0   865395979          3.285714  505   
41859     517        2     5.0   846450065          4.285714  516   
41860     518        2     4.0   945362514          3.572843  517   
41861     522        2     2.5  1391353926          3.166000  521   
41862     525        2     2.0  1024929394          3.659420  524   
41863     531        2     4.0  1243510104          2.977273  530   
41864     534        2     4.0   973376511          3.640264  533   
41865     535        2     3.0   838631374          3.015873  534   
41866     537        2     3.0   879521681          3.996743  536   
41867     548        2     3.0   857406875          3.376812  547   
41868     561        2     3.0  1172766441          3.597973  560   
41869     564        2     4.0   974839862          3.552463  563   
41870     575        2     4.0  1012598088          3.394881  574   
41871     580        2     3.5  1165900696          3.272777  579   
41872     590        2     3.0   848677637          3.483146  589   
41873     593        2     3.0   835464130          3.942857  592   
41874     595        2     2.0   965230397          3.938650  594   
41875     602        2     4.0   842360098          3.635659  601   
41876     603        2     4.0   868355874          3.868421  602   
41877     607        2     3.0  1118247388          3.653396  606   
41878     624        2     3.0  1019125424          2.894236  623   
41879     641        2     4.0   834636796          3.900000  640   
41880

In [67]:
df_sparse[2,:].nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]),
 array([  56,  100,  219,  239,  266,  284,  320,  321,  341,  472,  521,
         524,  525,  527,  617,  642,  699,  954,  966,  990, 1025, 1118,
        1253, 1359, 1455, 1590, 1834, 2010, 2156, 2162, 2173, 2212, 2273,
        2288, 2374, 2599, 2804, 3157, 4081, 4255, 4604, 5017, 5116, 5467,
        5472, 5888, 6363, 6536, 6579, 6892, 7708]))

In [85]:
j = 0
rating_vs = 3
k = 1
laplacian = None

df_j = df_sparse[:,j]
#Find set of users who rated item j rating
users = (df_j == rating_vs).nonzero()[0]
num_users = len(users)
#Of those users, how many rated item k the same as the original user?
df_k = df_sparse[users,k]
nz = df_k.nonzero()
nzk = df_k[nz[0]].toarray()
unq,cts = np.unique(nzk,return_counts=True)
ct = []

d = dict(zip(unq, cts))
d = {k:v for k,v in d.items() if k!=0}
ct.append(d)
#This dataframe now has rows which are films, columns which are ratings, and each entry has the number of times
#which that particular rating occurred for that particular film
ct_df = pd.DataFrame(ct)
numerator_cols = ct_df.columns
ct_df['rowsum'] = ct_df.sum(axis=1)

if laplacian is not None:
    ct_df[numerator_cols] = ct_df[numerator_cols].fillna(0) + laplacian
    ct_df['rowsum'] = ct_df['rowsum'].fillna(0) + laplacian * len(numerator_cols)
(ct_df[rating_vs].values/ct_df['rowsum'].values)[0]


0.69230769230769229

In [66]:
ct_df[rating_vs]/ct_df['rowsum']

0    0.692308
dtype: float64

In [69]:
??calculate_conditional

In [87]:
calculate_conditional(df_sparse,3,3,0,1)

0.69230769230769229

In [56]:
ct_df

rating   mid      prob
0         0.5     0  0.003137
1         0.5     1  0.006957
2         0.5     2  0.026866
3         0.5     3  0.038095
4         0.5     4  0.012500
5         0.5     5  0.007143
6         0.5     6  0.045902
7         0.5     7  0.061538
8         0.5     8  0.028571
9         0.5     9  0.006154
10        0.5    10  0.008889
11        0.5    11  0.030769
12        0.5    12  0.050000
13        0.5    13  0.020513
14        0.5    14  0.042105
15        0.5    15  0.008333
16        0.5    16  0.008511
17        0.5    17  0.023529
18        0.5    18  0.018000
19        0.5    19  0.038095
20        0.5    20  0.007767
21        0.5    21  0.017391
22        0.5    22  0.026667
23        0.5    23  0.042857
24        0.5    24  0.016514
25        0.5    25  0.061538
26        0.5    26  0.053333
27        0.5    27  0.030769
28        0.5    28  0.016667
29        0.5    29  0.044444
...       ...   ...       ...
90630     5.0  9036  0.080000
90631     5.0  9037  0.088889
90632     5.0  9038  0.088889
90633     5.0  9039  0.088889
90634     5.0  9040  0.080000
90635     5.0  9041  0.088889
90636     5.0  9042  0.088889
90637     5.0  9043  0.088889
90638     5.0  9044  0.080000
90639     5.0  9045  0.088889
90640     5.0  9046  0.088889
90641     5.0  9047  0.088889
90642     5.0  9048  0.080000
90643     5.0  9049  0.088889
90644     5.0  9050  0.080000
90645     5.0  9051  0.088889
90646     5.0  9052  0.088889
90647     5.0  9053  0.200000
90648     5.0  9054  0.088889
90649     5.0  9055  0.088889
90650     5.0  9056  0.088889
90651     5.0  9057  0.088889
90652     5.0  9058  0.088889
90653     5.0  9059  0.088889
90654     5.0  9060  0.088889
90655     5.0  9061  0.200000
90656     5.0  9062  0.088889
90657     5.0  9063  0.200000
90658     5.0  9064  0.088889
90659     5.0  9065  0.200000

[90660 rows x 3 columns]

In [45]:
rating_dict

{0: 670,
 0.5: 0,
 1.0: 0,
 1.5: 0,
 2.0: 0,
 2.5: 0,
 3.0: 0,
 3.5: 0,
 4.0: 0,
 4.5: 0,
 5.0: 1}

In [44]:
ct_df[ct_df['mid'] == 0]

rating  mid      prob
0           0    0  0.624890
9066        1    0  0.001177
18132       2    0  0.007061
27198       3    0  0.005590
36264       4    0  0.020300
45330       5    0  0.007061
54396       6    0  0.061489
63462       7    0  0.035010
72528       8    0  0.114445
81594       9    0  0.029126
90660      10    0  0.093851

In [12]:
np.unique(df_sparse.toarray(),return_counts=True,axis=1)

(array([[ 0.,  0.,  0., ...,  4.,  4.,  4.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  4.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))